name: Greetings

# issues like opened, edited, deleted
# seite: https://docs.github.com/de/actions/reference/workflows-and-actions/events-that-trigger-workflows#issues
on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      # repo url: https://github.com/actions/first-interaction
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "dotliff shrumps trumps pubic hair"
